# wrangler.toml - CloudFlare Worker Configuration

name = "topoglyph-cognitive-graph"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# KV Storage for graph nodes
[[kv_namespaces]]
binding = "TOPOGLYPH_KV"
id = "your_kv_namespace_id"
preview_id = "your_preview_kv_namespace_id"

# Environment variables
[env.production.vars]
# Set via: wrangler secret put OPENROUTER_API_KEY
# OPENROUTER_API_KEY = "your-openrouter-api-key"

[env.development.vars]
# OPENROUTER_API_KEY = "your-development-key"

# Worker configuration
[build]
command = "npm run build"

[limits]
# Increase limits for cognitive processing
duration_ms = 30000  # 30 seconds for complex queries